config/routes.rb
Woodlove::Application.routes.draw do

  root to: redirect('/catalogue')

  get 'catalogue', to: 'catalogue#index'

  get 'subcategories/:url', to: 'subcategories#show'
  resources :subcategories

  resources :categories

  namespace :admin do
    root to: 'index#index'
    get 'let_me_in_please_im_a_cat', to: 'index#enable_admin_access'
    get 'let_me_in_please_im_a_dog', to: 'index#disable_admin_access'

    #get 'items/:id/edit', to: 'items#edit'
    get 'items/update_popularity_points', to: 'items#update_popularity_points'
    resources :items
    resources :categories
    resources :brands

    get 'survey_users/update_data', to: 'survey_users#update_data', as: :update_data
    resources :survey_users

    get 'items/:id/delete', to: 'items#delete', as: :delete
  end

  namespace :api, path: 'api' do
    get 'cart/get', to: 'cart#get'
    post 'cart/item/add', to: 'cart#add_item'
    post 'cart/item/remove', to: 'cart#remove_item'
    post 'cart/item/inc', to: 'cart#inc_item'
    post 'cart/item/dec', to: 'cart#dec_item'

    post 'items/recent/clear', to: 'items#clear_recent'

    post 'survey/login', to: 'survey#login'
    post 'survey/next', to: 'survey#next'
    post 'survey/comment', to: 'survey#comment'
  end

  get '/items/:url', to: 'items#show'
  get '/categоries/:url', to: 'categories#show', as: :show
  get '/brands/:brand_url', to: 'categories#show', as: :show
  get '/cart', to: 'cart#show'
  #get '/:url', to: 'catalogue#url_processor'

  #resources :items #, only: :show

  get '/survey', to: 'survey#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :url, :name, :description, :title, :logo, :image_promo, :warranty, :is_published

  has_many :items
  #belongs_to :category

  has_attached_file :logo,  :styles => { :default => "330x70>" }
  has_attached_file :image_promo,  :styles => { :default => "1880x455>" }

  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :image_promo, :content_type => /\Aimage\/.*\Z/

  def header
    self.title
  end

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController

    def index
      @brands = Brand.all
    end

    def new
      @brand = Brand.new
      @header = "Новый Brand"
      @link_back = admin_brands_path
    end

    def edit
      @brand = Brand.find(params[:id])
      @header = "Редактирование Brand"
      @link_back = admin_brands_path
    end

    def create
      @brand = Brand.new(params[:brand])
      @brand.save!

      redirect_to admin_brands_path
    end

    def update
      @brand = Brand.find(params[:id])
      @brand.update_attributes(params[:brand])

      redirect_to admin_brands_path
    end

end

app/views/admin/brands/_brand_form.html.slim
= form_for [:admin, brand], html: {class: 'b-admin-form'} do |f|
  .b-admin-form-item
    = f.label        "url"
    = f.text_field   "url"

  .b-admin-form-item
    = f.label        "name"
    = f.text_field   "name"

  .b-admin-form-item
    = f.label        "title"
    = f.text_field   "title"

  .b-admin-form-item
    = f.label        "description"
    = f.text_area    "description"

  .b-admin-form-item
    = f.label        "warranty"
    = f.text_area    "warranty"

  .b-admin-form-item
    = f.label        "is_published"
    = f.check_box    "is_published"

  .b-admin-form-block-right
    .b-admin-form-block-right-item
      .b-admin-form-block-right-item-header ="Logo Picture"
      .b-admin-form-block-right-item-content
        - if brand.logo.present?
          img.b-admin-form-block-right-item-image src=brand.logo.url(:default)

        = f.label "logo", 'Выбрать картинку',  class: 'b-admin-form-item-button'
        = f.file_field "logo", hidden: 'hidden'

    .b-admin-form-block-right-item
      .b-admin-form-block-right-item-header ="Promo Picture"
      .b-admin-form-block-right-item-content
        - if brand.image_promo.present?
          img.b-admin-form-block-right-item-image src=brand.image_promo.url(:default)

        = f.label "image_promo", 'Выбрать картинку',  class: 'b-admin-form-item-button'
        = f.file_field "image_promo", hidden: 'hidden'


  .b-admin-form-item.m-no-label
    = f.submit

app/views/admin/brands/edit.html.slim
= render partial: 'brand_form', locals: {brand: @brand}

app/views/admin/brands/index.html.slim
.m-offset-bottom
  = link_to 'Новый Brand', new_admin_brand_path, class: 'b-admin-form-item-button'

- if @brands.present?
  .m-offset-bottom
  - @brands.each do |brand|
    div
      = link_to brand.title, edit_admin_brand_path(brand)

app/views/admin/brands/new.html.slim
= render partial: 'brand_form', locals: {brand: @brand}