config/routes.rb
Woodlove::Application.routes.draw do

  root to: redirect('/catalogue')

  get 'catalogue', to: 'catalogue#index'

  get 'subcategories/:url', to: 'subcategories#show'
  resources :subcategories

  resources :categories

  namespace :admin do
    root to: 'index#index'
    get 'let_me_in_please_im_a_cat', to: 'index#enable_admin_access'
    get 'let_me_in_please_im_a_dog', to: 'index#disable_admin_access'

    #get 'items/:id/edit', to: 'items#edit'
    get 'items/update_popularity_points', to: 'items#update_popularity_points'
    resources :items
    resources :categories
    resources :brands

    get 'survey_users/update_data', to: 'survey_users#update_data', as: :update_data
    resources :survey_users

    get 'items/:id/delete', to: 'items#delete', as: :delete
  end

  namespace :api, path: 'api' do
    get 'cart/get', to: 'cart#get'
    post 'cart/item/add', to: 'cart#add_item'
    post 'cart/item/remove', to: 'cart#remove_item'
    post 'cart/item/inc', to: 'cart#inc_item'
    post 'cart/item/dec', to: 'cart#dec_item'

    post 'items/recent/clear', to: 'items#clear_recent'

    post 'survey/login', to: 'survey#login'
    post 'survey/next', to: 'survey#next'
    post 'survey/comment', to: 'survey#comment'
  end

  get '/items/:url', to: 'items#show'
  get '/categоries/:url', to: 'categories#show', as: :show
  get '/brands/:brand_url', to: 'categories#show', as: :show
  get '/cart', to: 'cart#show'
  #get '/:url', to: 'catalogue#url_processor'

  #resources :items #, only: :show

  get '/survey', to: 'survey#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :desc, :desc_original, :link_to_original_item, :meta, :facts, :price, :price_original, :price_special, :title, :title_original, :picture, :picture2, :picture3, :picture4, :picture5, :url, :category_id, :is_published, :brand_id, :gender, :popularity_points

  belongs_to :category
  belongs_to :brand

  has_many :comments

  has_attached_file :picture,  :styles => { :large => "450x300>", :medium => "300x200>", :thumb => "150x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :picture2, :styles => { :large => "450x300>", :medium => "300x200>", :thumb => "150x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :picture3, :styles => { :large => "450x300>", :medium => "300x200>", :thumb => "150x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :picture4, :styles => { :large => "450x300>", :medium => "300x200>", :thumb => "150x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :picture5, :styles => { :large => "450x300>", :medium => "300x200>", :thumb => "150x100>" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  include ApplicationHelper

  def self.popular(limit = 6)
    ids = self.popular_ids(limit)
    orders = []
    ids.each_with_index {|id, index| orders[id]=index}

    Item.find(ids).sort_by{|i| orders[i.id]}
  end

  def self.popular_ids(limit = 6)
    items = self.popular_as_hash
    items_ids = items.sort{ |a,b| a[:points] <=> b[:points] }.reverse.map{|i|i[:id].to_i}
    items_ids
  end

  def self.popular_as_hash(limit = 6)
    items_liked = []
    items_best  = []
    items_total = []
    items       = []

    SurveyUser.all.each do |item|
      items_liked += item.get_data_liked
      items_best  += item.get_data_best
    end
    items_best += items_best
    items_total = items_liked + items_best

    items_total.uniq.each do |item|
      items.push({
        id: item,
        points: items_total.count(item)
      })
    end

    items
  end

  def meta_as_hash
    meta_raw = self[:meta]
    return [] if meta_raw.nil? || meta_raw.empty?
    meta_arr = []
    meta_raw.split(';').each do |meta_item|
      meta_item_parts = meta_item.split(':')

      if meta_item_parts.length > 1
        meta_arr << {
          name: meta_item_parts[0].strip.html_safe,
          value: meta_item_parts[1].strip.html_safe
        }
      end
    end
    meta_arr
  end

  def facts_as_hash
    facts_raw = self.facts
    return [] if facts_raw.nil? || facts_raw.empty?
    facts_arr = facts_raw.split("\n")
    facts_arr
  end

  def pictures
    pics_arr = []
    pics_arr << self.picture  if picture.present?
    pics_arr << self.picture2 if picture2.present?
    pics_arr << self.picture3 if picture3.present?
    pics_arr << self.picture4 if picture4.present?
    pics_arr << self.picture5 if picture5.present?
    pics_arr
  end

  def price_to_use
    self.price
  end

  #def to_param
  #  self.url
  #end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController

  include ItemsHelper

  def index
    @items = Item.all.sort_by{|i|i.title}
    @categories = Category.all
  end

  def show
    redirect_to edit_admin_item_path(Item.last)
  end

  def new
    @item = Item.new
    @header = "Новый Item"
    @link_back = admin_items_path
  end

  def edit
    @item = Item.find(params[:id])
    @header = "Редактирование Item"
    @link_back = admin_items_path
  end

  def create
    @item = Item.new(params[:item])
    @item.save!

    redirect_to admin_items_path
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])

    redirect_to admin_items_path
  end

  def delete
    #puts params
    #return;

    item = Item.find(params[:id])
    item.destroy if item.present?

    redirect_to admin_items_path
  end

  def destroy_picture
    item = Item.find(params[:id])

    if !item.nil?
      if params[:picture] == '1'
        item.picture.destroy
      else
        item["picture#{params[:picture]}"].destroy
      end
    end
    redirect_to action: :edit
  end

  def update_popularity_points
    items = Item.popular_as_hash(999)
    items.each do |item_data|
      item = Item.find(item_data[:id])
      item.popularity_points = item_data[:points]
      item.save!
    end

    redirect_to admin_items_path
  end

end

app/controllers/api/items_controller.rb
class Api::ItemsController < Api::ApiController

  include ItemsHelper

  def clear_recent
    if session[:recently_viewed_items].present?
      session[:recently_viewed_items] = nil
    end
    render json: {}
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  #include ApplicationHelper

  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #@item = Item.find(params[:id])
    @item = Item.where(url: params[:url]).last
    raise ActiveRecord::RecordNotFound if @item.nil?

    @scripts_id = 'item-show'
    @cart = get_user_cart

    @random_items = Item.where(category_id: @item.category.id).shuffle
    if @item.gender != nil
      @random_items = @random_items.select{|i| (i.gender == @item.gender || i.gender == "unisex") && i.id != @item.id}
    end

    @item_warranty = @item.brand.present? && @item.brand.warranty.present? ? @item.brand.warranty : nil
    @item_facts    = @item.facts_as_hash
    @item_meta     = @item.meta_as_hash

    add_item_to_recents

    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.json { render json: @item }
    #end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private

  def add_item_to_recents
    if !session[:recently_viewed_items].present?
      session[:recently_viewed_items] = []
    end
    return if session[:recently_viewed_items].index(@item.id) != nil
    session[:recently_viewed_items].push(@item.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def item_path(item)
    return "/items/#{item.url}"
  end

  def recently_viewed_items
    if session[:recently_viewed_items].present? && session[:recently_viewed_items].is_a?(Array)
      return Item.find(session[:recently_viewed_items])
    end
    return []
  end

end

app/views/items/_button_add.html.slim
ruby:
  item ||= nil
  cart ||= nil

- if item.present?
  .b-layout-item-button-buy-wrapper role="b-button-add" data-config=item_control_config(item)
    - if cart.item_present?(item)
      .b-layout-item-button-buy-already-in-cart role="b-button-add-in-cart" data-visible="true"
        .b-layout-item-button-buy-already-in-cart-text ="Добавлено в "
        a.b-layout-item-button-buy-already-in-cart-link href="/cart" ="корзину"
      button.b-button-emphasis role="b-button-add-button" data-state="order"
        span class="button-text" role="b-button-add-button-text-add" data-visible="false" ="Добавить в корзину"
        span class="button-text" role="b-button-add-button-text-order" data-visible="true" ="Оформить заказ"

    - else
      .b-layout-item-button-buy-already-in-cart role="b-button-add-in-cart" data-visible="false"
        .b-layout-item-button-buy-already-in-cart-text ="Добавлено в "
        a.b-layout-item-button-buy-already-in-cart-link href="/cart" ="корзину"
      button.b-button-emphasis role="b-button-add-button" data-state="add"
        span class="button-text" role="b-button-add-button-text-add" data-visible="true" ="Добавить в корзину"
        span class="button-text" role="b-button-add-button-text-order" data-visible="false" ="Оформить заказ"

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title_original %><br />
    <%= f.text_field :title_original %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :desc_original %><br />
    <%= f.text_area :desc_original %>
  </div>
  <div class="field">
    <%= f.label :meta %><br />
    <%= f.text_field :meta %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :price_original %><br />
    <%= f.number_field :price_original %>
  </div>
  <div class="field">
    <%= f.label :price_special %><br />
    <%= f.number_field :price_special %>
  </div>
  <div class="field">
    <%= f.label :link_to_original_item %><br />
    <%= f.text_field :link_to_original_item %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_gallery.html.slim
ruby:
  pictures ||= []

- if !pictures.empty?
  .b-layout-item-pictures-wrapper role="bm-item-gallery"
    .b-layout-item-picture-zoom role="bm-item-gallery-zoom-wrapper" data-visible="false"
      .b-layout-item-picture-zoom-loader.bm-spinner data-loading="true" role="bm-item-gallery-zoom-loader"
    .b-layout-item-picture-large data-original-image=pictures.first.url(:original) role="bm-item-gallery-image-large"
      = image_tag pictures.first.url(:large), class: 'b-layout-item-picture-large-image', role: 'bm-item-gallery-image-large-picture'
      .b-layout-item-picture-large-overlay role="bm-item-gallery-image-large-overlay"

    - if pictures.length > 1
      .b-layout-item-picture-thumbs-wrapper
        - pictures.each_with_index do |picture, i|
          .b-layout-item-picture-thumb class="#{'m-active' if i == 0}" data-large-image=picture.url(:large) data-original-image=picture.url(:original) role="bm-item-gallery-image-thumb"
            = image_tag picture.url(:thumb), class: 'b-layout-item-picture-thumb-image'
      /.b-layout-item-picture-thumb
      /.b-layout-item-picture-thumb
      /.b-layout-item-picture-thumb
      /.b-layout-item-picture-thumb

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= item.title_original %></td>
    <td><%= item.desc %></td>
    <td><%= item.desc_original %></td>
    <td><%= item.meta %></td>
    <td><%= item.price %></td>
    <td><%= item.price_original %></td>
    <td><%= item.price_special %></td>
    <td><%= item.link_to_original_item %></td>
  </tr>
<% end %>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.slim
.b-layout-item
  .b-layout-item-content-left
    = render partial: 'items/gallery', locals: {pictures: @item.pictures}

  .b-layout-item-content-right
    .b-layout-item-title = @item.title
    .b-layout-item-price = "-#{@item.price}"
    .b-layout-item-description
      = @item.desc
    = render partial: 'items/button_add', locals: {item: @item, cart: @cart}

    - if !@item_facts.empty?
      .b-layout-item-facts
        .b-layout-item-facts-header ="Факты"

        - @item_facts.each do |fact|
          .b-layout-item-facts-item =fact


    - if !@item_meta.empty?
      .b-layout-item-specs
        .b-layout-item-specs-header ="Характеристики"

        - @item_meta.each do |meta|
          .b-layout-item-specs-item
            .b-layout-item-specs-item-label =meta[:name]
            .b-layout-item-specs-item-text =meta[:value]

    - if !@item_warranty.nil?
      .b-layout-item-warranty
        .b-layout-item-warranty-header ="Гарантия"
        .b-layout-item-warranty-text =@item_warranty

    /.b-layout-item-button-buy-wrapper
      button.b-button-emphasis ="+ Добавить в корзину"

- if @random_items.present? && @random_items.length > 0
  = render partial: 'ui/random', locals: {items: @random_items, header: "Случайные товары из этой категории:"}